Tensorflow Fundamental concepts of tensors

Overview:

1.Intro to tensors

2.Get info from tensors

3.Manipulating tensors

4.Tensors & NumPy

5.Use @tf.function (a way to speed up regular Python functions)

6.Use GPUs with Tensorflow (or TPUs)

In [ ]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


###Create tensors with 'tf.constant()'

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check num of dimension of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of vector
vector.ndim

1

In [ ]:
#create a matrix (matrix = more that 1D)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create new matrix
new_matrix = tf.constant([[10., 8.],[1., 2.],[7., 3.]], dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 1.,  2.],
       [ 7.,  3.]], dtype=float16)>

In [ ]:
new_matrix.ndim

2

In [ ]:
#Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]],
                       [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Scalar: a single number -- 0D

Vector: a number with direction (eg speed & direction)-- 1D

Matrix: a 2D array of numbers

Tensor: an N-dimension array of numbers 

###Create tensors with 'tf.Variable'

In [ ]:
#Create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,8])
unchangeable_tensor = tf.constant([10,8])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [ ]:
# change the value of elements in the tensors
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  8], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(11)
unchangeable_tensor
#note that tf.constant cannot be assigned as it is constant!

AttributeError: ignored

🔑Note: Rarely in practice we need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this for us.

However, if in doubt, use `tf.constant` and change it later if needed

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2)) #output random values from normal distribution

random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor


In [ ]:
#shuffle the data eg images of ramen and spaghetti so they are out of order (random)
#so that the model/NN doesn't fixed on learning one subjects

#Shuffle a tensor 
not_shuffled = tf.constant([[10,8],
                            [3,4],
                            [2,5]])

#shuffle not-shuffled tensor (randomly shuffle along its first dimension)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  8]], dtype=int32)>

In [ ]:
#Global level random seed produce the same shuffle result
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled, seed=42) #Operation level

#if only operation level seed is set, the shuffle result would differ

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  8],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

###Other ways to make tensors

> Indented block



In [ ]:
#Create a tensor of all ones
tf.ones([10,8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeroes
tf.zeros(shape=(3,4)) #tuple

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on GPU (much faster for numerical computing).


In [ ]:
# Turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) #create a NumPy array between 1 and 25
numpy_A
#X = tf.constant(some_matrix) #capital for matrix or tensor
#y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#convert that NumPy array into tensor
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

NOTE: to change the shape of tensor, the new elements must add up to give the same number of elements in original array.

Eg as above, Ori is 24, 2x3x4 = 24
OR below, 3x8 = 24

In [ ]:
A = tf.constant(numpy_A, shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

### Getting information from tensors

Tensor attributes:

* Shape-->The length(num of element) of each of dimension of a tensor --> tensor.shape
* Rank-->Num of tensor dimensions. A scalar=rank0, vector=rank2, matrix=rank2, tensor=rankn-->tensor.ndim
* Axis or dimension-->a particular dimension of a tensor--> tensor[0],tensor[:,1]...
* Size-->total num of items in tensor--> tf.size(tensor)

In [ ]:
#create rank 4 tensor (4D)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Num of dimension (rank):", rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1]) #grab last index
print("Total num of elements in our tensor:",tf.size(rank_4_tensor))
print("Total num of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Num of dimension (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total num of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total num of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed like Python lists

In [ ]:
eg_list = [1,2,3,4]
eg_list[:2]

[1, 2]

In [ ]:
#Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#Get the 1st element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:] # : alone = get the whole thing

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Get the 1st element from each dimension from each index except for second last
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2D)
rank_2_tensor = tf.constant([[10,8],
                             [3,4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each rows in the rank 2 tensor
rank_2_tensor[:,-1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 4], dtype=int32)>

In [ ]:
#Add extra dimension (turn rank 2 into rank 3 tensor)
#change the shape only, elements stay the same
rank_3_tensor = rank_2_tensor[...,tf.newaxis] 
#... = :,:,: -->get all elements in axis before the last one
#add a new axis in the end --> tf.newaxis, in NumPy = None
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 8]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 8]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis--added dimension is in front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  8],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1) #added extra dimension in the middle

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  8]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

Default python operations:
* `+`,`-`,`*`,`/`


In [ ]:
# Values can be added to a tensor using the addition operator
tensor = tf.constant([[10,8],
                      [3,4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged!
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Do this if we want to change the ori tensor
#tensor = tensor + 10
#tensor

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  80],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -2],
       [-7, -6]], dtype=int32)>

In [ ]:
# tensorflow built-in fn --built in fn will speed up operations
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  80],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations

matrixmultiplication.xyz

There are 2 rules for tensors (or matrices) need to fulfill  if we're going to matrix multiply them:

1. The inner dimensions must match, eg: 3x(3) and (3)x2 
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in Tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  8]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [ ]:
tensor * tensor  #element wise, so the products are different

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  64],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#Create another (3,2) tensor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Matrix multiplication tensors of same shape
#X @ Y
#tf.matmul(X,Y)
# BOTH ARE INVALID SIZE

In [ ]:
# Ori Y shape
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Change shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2,3)).shape
#Inner dimension match so they can be multiplied

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Multiply X by reshape Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#Use tensorflow built in function (matmul) -- dot product
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# See what happens if we change shape of X instead Y
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# See the shape
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
#Dimension of result = outer dimension = 2x2

In [ ]:
# Can do the same with transpose
# transpose flip the axis whereas reshape shuffle num arounf to get the shape we want
tf.transpose(X)
# X = (3,2) ---> (2,3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
#check each of these shapes
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product

We can perform matrix multiplication using:
*`tf.matmul()`
*`tf.tensordot()`
*`@`



In [ ]:
#Remind X and Y
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Perform dot product on X and Y (requires X and Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X nad Y (reshape)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Notice transpose and reshape has diff results

In [ ]:
#Check the values of Y , reshape Y and transposed Y
print("Normal Y")
print(Y, "\n") # "\n" is for newline

print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, we will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

The default datatype would be int32 (actually depends on the data inside the tensor) but sometimes we want to change it

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
#Create a new tensor with default datatype (int32)
C = tf.constant([8, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 10], dtype=int32)>,
 tf.int32)

NOTE: Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory

By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy.

**This is from tensorflow doc**

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 8., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
# float 32 to float16
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16,E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 8., 10.], dtype=float16)>,
 tf.float16)

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
I = tf.constant([-8, -10])
I

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -8, -10], dtype=int32)>

In [ ]:
#Get absolute value
tf.abs(I)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the min
* Get the max
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
# Create a random tensor with values bet 0 and 100 of size 50
F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([40,  6, 82, 41, 34, 67, 55, 50,  0,  4, 88,  3,  1, 97, 70, 93, 33,
       31, 20, 77, 25, 41, 36, 26, 27, 56, 71, 69, 90, 31, 77, 14,  2, 32,
       88, 88, 90, 22, 17, 28, 72,  5, 70, 60, 33, 78, 63,  3, 46, 41])>

In [ ]:
# Check size, shape and number of dimension
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#Find the mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
# Find the sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2293>

In [ ]:
#import tensorflow_probability as tfp
#tfp.stats.variance(F)
# Find variance
#x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=862.4405>

In [ ]:
#Find standard deviation
#this fn requires fp32 format--complex data
tf.math.reduce_std(tf.cast(F, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=29.367336>

###Find the positional max and min

In [ ]:
# Create a new tensor for finding positonal max and min
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find positional max
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find max value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find positional max
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Index on our largest value position
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
H_squeezed = tf.squeeze(H) #SQUEEZE REMOVE DIMENSION OF SIZE 1 FROM THE SHAPE OF A TENSOR
H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One hot encoding

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] #could be red, green, blue,purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=4) # 4 total elements in some_list, therefore depth =4




<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specified custom values for one hot encoding
#rarely used coz ML loves numbers
tf.one_hot(some_list, depth=4, on_value="I love deep learning lol", off_value="I love cats")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning lol', b'I love cats', b'I love cats',
        b'I love cats'],
       [b'I love cats', b'I love deep learning lol', b'I love cats',
        b'I love cats'],
       [b'I love cats', b'I love cats', b'I love deep learning lol',
        b'I love cats'],
       [b'I love cats', b'I love cats', b'I love cats',
        b'I love deep learning lol']], dtype=object)>

### Squaring, log, square root

In [ ]:
#Create a new tensor
I = tf.range(1,10)
I


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root
tf.sqrt(tf.cast(I, dtype=tf.float32)) #this fn can't use data type int32

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Log
tf.math.log(tf.cast(I, dtype=tf.float32)) #this fn can't use data type int32

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow interacts with NumPy arrays

NumPy is a fundamental package for scientific computing with Python

Note: One of the main differences between a Tensorflow tensor and a NumPy array is that a Tensorflow tensor can be run on a GPU or TPU (for faster numerical processing)

In [ ]:
#Create a tensor directly from a NumPY array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#with this numpy array, we can access the value through index position
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# Default type of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

#NOTE: converting NumPy array into tensors may results in different datatype


(tf.float64, tf.float32)

### Finding access to GPUs

* To access GPU, go to Runtime--> Change Runtime type --> Select GPU

Note: Availability of GPU in Google Colabs varies over time to provide access for free.

Often include:

* NVDIA K80s
* T4s
* P4s
* P100s

In [ ]:
import tensorflow as tf
#check what device the tf is running on from
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Sep 21 13:46:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 **Note:** If we have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible