### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant() & 2. Find the shape, rank and size of the tensors you created in 1.

In [24]:
import tensorflow as tf

#Create vector
vector = tf.constant([10,8])
vector, vector.shape, vector.ndim, tf.size(vector)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>,
 TensorShape([2]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [25]:
#Create Scalar
scalar = tf.constant([10,8])
scalar, scalar.shape, scalar.ndim, tf.size(scalar)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>,
 TensorShape([2]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [26]:
#Create matrix
matrix = tf.constant([[10,8],[8,10]])
matrix, matrix.shape, matrix.ndim, tf.size(matrix)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  8],
        [ 8, 10]], dtype=int32)>,
 TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [27]:
#Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]],
                       [[13,14,15],[16,17,18]]])
tensor, tensor.shape, tensor.ndim, tf.size(tensor)

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 TensorShape([3, 2, 3]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=18>)

### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [31]:

random_1 = tf.random.uniform(shape=(5,300), minval=0, maxval=1)

random_2 = tf.random.uniform(shape=(5,300), minval=0, maxval=1)

#OR
#F = tf.constant(np.random.randint(0,1,size=5,300))
#F


random_1, random_2


(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.28993773, 0.7334968 , 0.9718391 , ..., 0.25418782, 0.547035  ,
         0.00398028],
        [0.58575845, 0.75144076, 0.83544993, ..., 0.20461595, 0.24232769,
         0.48856854],
        [0.10342443, 0.63038385, 0.11465168, ..., 0.99103284, 0.68051946,
         0.30772257],
        [0.9893285 , 0.8294014 , 0.08697784, ..., 0.21644545, 0.46166873,
         0.9281728 ],
        [0.53131926, 0.940225  , 0.16743708, ..., 0.18726182, 0.98115396,
         0.24402535]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.95500207, 0.3267312 , 0.16876781, ..., 0.12640107, 0.34685552,
         0.11175907],
        [0.9359951 , 0.65129554, 0.81837225, ..., 0.9420198 , 0.7317295 ,
         0.91028523],
        [0.99249184, 0.3906201 , 0.0694747 , ..., 0.7365279 , 0.29552162,
         0.5620011 ],
        [0.8870145 , 0.49145818, 0.8243786 , ..., 0.79161763, 0.02861023,
         0.01896846],
        [0.47644

### Multiply the two tensors you created in 3 using matrix multiplication.

In [32]:
#Both random_1 and random_2 has same shape so they need to be reshape
#NOTE: INNER DIMENSION MUST MATCH
#random_1 shape maintained (5,300)
#random_2 rehape into (300,,5)

# Reshape random_2
tf.reshape(random_2, shape=(300,5))



<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
array([[0.95500207, 0.3267312 , 0.16876781, 0.3783468 , 0.9884498 ],
       [0.62168825, 0.46569705, 0.47134852, 0.13195682, 0.15151417],
       [0.39525962, 0.08442354, 0.7734182 , 0.88399875, 0.5040077 ],
       ...,
       [0.9391004 , 0.69949055, 0.8694823 , 0.7259325 , 0.0281477 ],
       [0.0398618 , 0.8614689 , 0.4769528 , 0.4495734 , 0.47422826],
       [0.4094231 , 0.38021767, 0.49815536, 0.45159924, 0.30631936]],
      dtype=float32)>

In [33]:
#Multiply random_1 by reshape random_2
random_1 @ tf.reshape(random_2, shape=(300,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.22719 , 74.14203 , 70.682205, 72.09761 , 76.85428 ],
       [80.25902 , 77.08526 , 72.59862 , 71.86126 , 74.86664 ],
       [79.85585 , 79.55744 , 75.057594, 71.51347 , 76.84653 ],
       [83.151215, 82.47198 , 76.0844  , 73.65195 , 81.77626 ],
       [79.7343  , 73.72511 , 70.91947 , 70.09284 , 74.46483 ]],
      dtype=float32)>

In [34]:
# OR Tensorflow  Matrix multiplication built in function
tf.matmul(random_1 ,tf.reshape(random_2, shape=(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.22719 , 74.14203 , 70.682205, 72.09761 , 76.85428 ],
       [80.25902 , 77.08526 , 72.59862 , 71.86126 , 74.86664 ],
       [79.85585 , 79.55744 , 75.057594, 71.51347 , 76.84653 ],
       [83.151215, 82.47198 , 76.0844  , 73.65195 , 81.77626 ],
       [79.7343  , 73.72511 , 70.91947 , 70.09284 , 74.46483 ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

Note: Perform dot product on random_1 and random_2 requires random_1 OR random_2 to be transposed


In [35]:
#Using tf.tensordot
tf.tensordot(tf.transpose(random_1),random_2 , axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.0584993 , 1.3626794 , 1.4246296 , ..., 1.712469  , 0.8279957 ,
        0.8052545 ],
       [3.2131436 , 2.0196843 , 1.5964615 , ..., 2.3898292 , 1.4388951 ,
        1.4240185 ],
       [1.9808015 , 1.0625819 , 0.9505743 , ..., 1.1465589 , 1.0603961 ,
        0.986483  ],
       ...,
       [1.6990718 , 0.8366297 , 0.48356223, ..., 1.2194327 , 0.6215215 ,
        0.8330957 ],
       [2.3016202 , 1.493756  , 0.85434777, ..., 1.6528772 , 1.0244654 ,
        0.97347975],
       [1.7060785 , 1.0611284 , 1.2208333 , ..., 1.5437111 , 0.58657616,
        0.7104777 ]], dtype=float32)>

In [36]:
# Using matmul
tf.matmul(tf.transpose(random_1),random_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.0584993 , 1.3626794 , 1.4246296 , ..., 1.712469  , 0.8279957 ,
        0.8052545 ],
       [3.2131436 , 2.0196843 , 1.5964615 , ..., 2.3898292 , 1.4388951 ,
        1.4240185 ],
       [1.9808015 , 1.0625819 , 0.9505743 , ..., 1.1465589 , 1.0603961 ,
        0.986483  ],
       ...,
       [1.6990718 , 0.8366297 , 0.48356223, ..., 1.2194327 , 0.6215215 ,
        0.8330957 ],
       [2.3016202 , 1.493756  , 0.85434777, ..., 1.6528772 , 1.0244654 ,
        0.97347975],
       [1.7060785 , 1.0611284 , 1.2208333 , ..., 1.5437111 , 0.58657616,
        0.7104777 ]], dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [37]:
random_3 = tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1)
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[8.6833549e-01, 4.0029573e-01, 9.7652793e-02],
        [6.5629220e-01, 7.8344440e-01, 6.7158294e-01],
        [5.1425922e-01, 6.5284216e-01, 9.0389073e-01],
        ...,
        [8.2239759e-01, 3.6446118e-01, 2.3877645e-01],
        [7.3562336e-01, 4.6390355e-01, 5.7962704e-01],
        [5.8081901e-01, 4.6580565e-01, 6.9471157e-01]],

       [[6.2129974e-01, 1.4857924e-01, 4.7775817e-01],
        [8.2918358e-01, 6.4042461e-01, 8.0004072e-01],
        [6.0307133e-01, 2.3163080e-01, 7.7755713e-01],
        ...,
        [4.5889008e-01, 6.3546848e-01, 4.7102058e-01],
        [5.5991137e-01, 4.5373869e-01, 2.9823959e-01],
        [6.1273575e-01, 2.1640837e-01, 3.4563184e-02]],

       [[1.1873186e-01, 5.6669974e-01, 5.0377405e-01],
        [5.3928769e-01, 3.5187113e-01, 9.0724349e-01],
        [9.8921180e-01, 3.4053648e-01, 3.0117178e-01],
        ...,
        [1.6631329e-01, 2.1343088e-01, 6.2214994e-01],
        [9.5148587e-01

### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [38]:
#Minimum
tf.reduce_min(random_3)

<tf.Tensor: shape=(), dtype=float32, numpy=9.059906e-06>

In [39]:
#maximum
tf.reduce_max(random_3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99998724>

### 8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [47]:
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]), shape=(1, 224, 224, 3))
H

#OR

#I = tf.random.uniform(shape=[1, 224, 224, 3])

#I

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.42612267, 0.09686017, 0.16105258],
         [0.1487099 , 0.04513884, 0.9497483 ],
         [0.4393103 , 0.28527975, 0.96971095]],

        [[0.73308516, 0.5657046 , 0.33238935],
         [0.8838178 , 0.87544763, 0.56711245],
         [0.8879347 , 0.47661996, 0.42041814],
         ...,
         [0.7716515 , 0.9116473 , 0.3229897 ],
         [0.43050945, 0.83253574, 0.45549798],
         [0.29816985, 0.9639522 , 0.3316357 ]],

        [[0.41132426, 0.2179662 , 0.53570235],
         [0.5112119 , 0.6484759 , 0.8894886 ],
         [0.42459428, 0.20189774, 0.85781324],
         ...,
         [0.02888799, 0.3995477 , 0.11355484],
         [0.68524575, 0.04945195, 0.17778492],
         [0.97627187, 0.79811585, 0.9411576 ]],

        ...,

        [[0.9019445 , 0.27011132, 

In [48]:
H.shape

TensorShape([1, 224, 224, 3])

In [49]:
H_squeezed = tf.squeeze(H) 

H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.42612267, 0.09686017, 0.16105258],
         [0.1487099 , 0.04513884, 0.9497483 ],
         [0.4393103 , 0.28527975, 0.96971095]],
 
        [[0.73308516, 0.5657046 , 0.33238935],
         [0.8838178 , 0.87544763, 0.56711245],
         [0.8879347 , 0.47661996, 0.42041814],
         ...,
         [0.7716515 , 0.9116473 , 0.3229897 ],
         [0.43050945, 0.83253574, 0.45549798],
         [0.29816985, 0.9639522 , 0.3316357 ]],
 
        [[0.41132426, 0.2179662 , 0.53570235],
         [0.5112119 , 0.6484759 , 0.8894886 ],
         [0.42459428, 0.20189774, 0.85781324],
         ...,
         [0.02888799, 0.3995477 , 0.11355484],
         [0.68524575, 0.04945195, 0.17778492],
         [0.97627187, 0.79811585, 0.9411576 ]],
 
        ...,
 
        [[0.9019445 , 0.27011132

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [61]:
random_4 = tf.random.uniform(shape=[10], minval=1, maxval=50)
random_4

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([40.354645 , 25.39109  , 19.156479 , 45.681503 , 32.24446  ,
        9.92275  , 32.258057 , 14.573722 ,  3.0712857, 42.267498 ],
      dtype=float32)>

In [56]:
#find positional max
tf.argmax(random_4)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [57]:
#Index on max value position
random_4[tf.argmax(random_4)]

<tf.Tensor: shape=(), dtype=float32, numpy=44.725937>

### 10. One-hot encode the tensor you created in 9.

In [62]:
#One hot encode random_4
tf.one_hot(tf.cast(random_4,dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>